env:
    global:
        - PACKAGE="__all__"
        - SUBLIME_TEXT_VERSION="3"


before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
    # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
    - export DISPLAY=:99.0;
    - sh -e /etc/init.d/xvfb start

install:
    # bootstrap the testing environment
    - sh travis.sh bootstrap

script:
    # testing syntax_test files
    - sh travis.sh run_syntax_tests

notifications:
    email: false
